spring.application.name=com.simple.crud.api


spring.datasource.url=jdbc:postgresql://localhost:5432/my-test-database
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword1881*!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true